name: Monitor 1-click Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - stage
          - prod
      commitSha:
        description: 'Commit Sha to deploy'
        required: true
        type: string
env:
  DOCKER_IMAGE_NAME: mozilla/blurts-server
jobs:
  pull_retag_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.commitSha }}

      - name: Retag image
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }}${{ inputs.commitSha }} ${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.environment }}-${{ inputs.commitSha }}
          
      - name: Redeploy image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.environment }}-${{ inputs.commitSha }}