name: Retag and Push Docker Image on Release
# GH release should always create a tag automatically
on:
  push:
    tags:
      - '*'

jobs:
  retag-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract tag
      id: extract_tag
      run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"
  
    - name: Extract commit SHA
      id: extract_sha
      run: echo "::set-output name=COMMIT_SHA::${GITHUB_SHA}"

    - name: Pull Docker image with commit tag
      run: docker pull mozilla/blurts-server:${{ steps.extract_sha.outputs.COMMIT_SHA }}

    - name: Tag Docker image with release tag
      run: docker tag mozilla/blurts-server:${{ steps.extract_sha.outputs.COMMIT_SHA }} mozilla/blurts-server:${{ steps.extract_tag.outputs.TAG }}

    - name: Push Docker image with release tag
      run: docker push mozilla/blurts-server:${{ steps.extract_tag.outputs.TAG }}
